<?php

namespace Database\Seeders;

use App\Models\KeuanganSubKomponenDetail;
use Illuminate\Database\Seeder;

class KeuanganSubKomponenDetailSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            ['kode_pok' => '1.1.1', 'kode_owp' => '1.1.1.01', 'nama_komponen_detail' => 'Equipment and supporting facilities for seed institution'],
            ['kode_pok' => '1.1.2', 'kode_owp' => '1.1.2.01', 'nama_komponen_detail' => 'Facilitation of Foundation seed for BBH'],
            ['kode_pok' => '1.1.2', 'kode_owp' => '1.1.2.02', 'nama_komponen_detail' => 'Facilitation of Foundation seed for Produsen/Penangkar'],
            ['kode_pok' => '1.1.3', 'kode_owp' => '1.1.3.01', 'nama_komponen_detail' => 'Technical Guidance for BBH staff'],
            ['kode_pok' => '1.1.4', 'kode_owp' => '1.1.4.01', 'nama_komponen_detail' => 'Technical Guidance on Seed Regulation and Certification Bimtek sertifikasi perbenihan dan teknis penerapan sistem jaminan mutu benih'],
            ['kode_pok' => '1.1.4', 'kode_owp' => '1.1.4.02', 'nama_komponen_detail' => 'Seed Certification dan Pelabelan Benih oleh BPSB untuk Benih hasil Produksi BBH dan Penangkar'],
            ['kode_pok' => '1.1.5', 'kode_owp' => '1.1.5.01', 'nama_komponen_detail' => 'Technical Guidance for seed producers'],
            ['kode_pok' => '1.1.5', 'kode_owp' => '1.1.5.02', 'nama_komponen_detail' => 'Facilitation of Seed Production Facilities and Equipment (Screen House, drying and storage of seeds)'],
            ['kode_pok' => '1.1.5', 'kode_owp' => '1.1.5.03', 'nama_komponen_detail' => 'Seed production facilitation for seed producer'],
            ['kode_pok' => '1.2.1', 'kode_owp' => '1.2.1.01', 'nama_komponen_detail' => 'Facilitation Equipment and supporting material for pesticide laboratories'],
            ['kode_pok' => '1.2.1', 'kode_owp' => '1.2.1.02', 'nama_komponen_detail' => 'Facilitation Equipment and supporting material for Pest observer Laboratories LPHP/LAH'],
            ['kode_pok' => '1.2.1', 'kode_owp' => '1.2.1.03', 'nama_komponen_detail' => 'Establishment Mobile clinics'],
            ['kode_pok' => '1.2.1', 'kode_owp' => '1.2.1.04', 'nama_komponen_detail' => 'Establishment of IPM Clinics'],
            ['kode_pok' => '1.2.1', 'kode_owp' => '1.2.1.05', 'nama_komponen_detail' => 'Equipment for the IPM Clinics'],
            ['kode_pok' => '1.2.1', 'kode_owp' => '1.2.1.06', 'nama_komponen_detail' => 'Equipment for pest observers (mobile electronic devices and mini-kits)'],
            ['kode_pok' => '1.2.2', 'kode_owp' => '1.2.2.01', 'nama_komponen_detail' => 'Exploration, Purification and Reproduction of Biological Control Agencies at LPHP and LAH'],
            ['kode_pok' => '1.2.3', 'kode_owp' => '1.2.3.01', 'nama_komponen_detail' => 'Provision of information materials on OPT Control/Climate Change Impact Management'],
            ['kode_pok' => '1.2.3', 'kode_owp' => '1.2.3.02', 'nama_komponen_detail' => 'Technical Guidance for pest observers'],
            ['kode_pok' => '1.2.4', 'kode_owp' => '1.2.4.01', 'nama_komponen_detail' => 'Technical Guidance for IPM Clinics Personel'],
            ['kode_pok' => '1.2.4', 'kode_owp' => '1.2.4.02', 'nama_komponen_detail' => 'Regular efficiency tests for IPM Clinics Products'],
            ['kode_pok' => '1.2.4', 'kode_owp' => '1.2.4.03', 'nama_komponen_detail' => 'Sosialisasi Biopestisida dan/ Pupuk Organik ke Petani'],
            ['kode_pok' => '1.2.4', 'kode_owp' => '1.2.4.04', 'nama_komponen_detail' => 'Demo farms the use of biopesticides/biofertilizers'],
            ['kode_pok' => '1.3.1', 'kode_owp' => '1.3.1.01', 'nama_komponen_detail' => 'Technical Guidance for farmers on irrigation Management'],
            ['kode_pok' => '1.3.1', 'kode_owp' => '1.3.1.02', 'nama_komponen_detail' => 'Construction of irrigation civil works and Equipment'],
            ['kode_pok' => '1.3.1', 'kode_owp' => '1.3.1.03', 'nama_komponen_detail' => 'Technical Guidance for farmers on micro irrigation Management'],
            ['kode_pok' => '1.3.1', 'kode_owp' => '1.3.1.04', 'nama_komponen_detail' => 'Construction of Micro irrigation civil works and Equipment'],
            ['kode_pok' => '1.3.2', 'kode_owp' => '1.3.2.01', 'nama_komponen_detail' => 'Facilitation of soil and pH testing equipment'],
            ['kode_pok' => '1.3.2', 'kode_owp' => '1.3.2.02', 'nama_komponen_detail' => 'Facilitation of the soil microbiology production unit'],
            ['kode_pok' => '1.3.3', 'kode_owp' => '1.3.3.01', 'nama_komponen_detail' => 'Participatory improving land and water conservation Activities'],
            ['kode_pok' => '1.3.3', 'kode_owp' => '1.3.3.02', 'nama_komponen_detail' => 'Workshops and consultations with private sector'],
            ['kode_pok' => '2.1.1', 'kode_owp' => '2.1.1.01', 'nama_komponen_detail' => 'HCDP Workshops and Socialization'],
            ['kode_pok' => '2.1.2', 'kode_owp' => '2.1.2.01', 'nama_komponen_detail' => 'Providing necessary non-consumable inputs for selected commodities'],
            ['kode_pok' => '2.1.3', 'kode_owp' => '2.1.3.01', 'nama_komponen_detail' => 'Facilitation for the Pest Management Area'],
            ['kode_pok' => '2.1.3', 'kode_owp' => '2.1.3.02', 'nama_komponen_detail' => 'Power Sprayer for fruit cluster'],
            ['kode_pok' => '2.1.3', 'kode_owp' => '2.1.3.03', 'nama_komponen_detail' => 'Knapsack Sprayer for Vegetable and Medicinal cluster'],
            ['kode_pok' => '2.1.3', 'kode_owp' => '2.1.3.04', 'nama_komponen_detail' => 'Insect net for Pest Control in Shallot HCD'],
            ['kode_pok' => '2.1.4', 'kode_owp' => '2.1.4.01', 'nama_komponen_detail' => 'Consultations with research stakeholders, identifying the location-specific for HCs'],
            ['kode_pok' => '2.1.4', 'kode_owp' => '2.1.4.02', 'nama_komponen_detail' => 'Demo Farm for Implementation of the GAP specific location'],
            ['kode_pok' => '2.1.5', 'kode_owp' => '2.1.5.01', 'nama_komponen_detail' => 'production equipment support for fruit cluster'],
            ['kode_pok' => '2.1.5', 'kode_owp' => '2.1.5.02', 'nama_komponen_detail' => 'production equipment support for vegetables and medicinal plant cluster'],
            ['kode_pok' => '2.1.6', 'kode_owp' => '2.1.6.01', 'nama_komponen_detail' => 'Facilitation Agriculture Machinery'],
            ['kode_pok' => '2.2.1', 'kode_owp' => '2.2.1.01', 'nama_komponen_detail' => 'Consultations and workshops with research stakeholders, short-listing of SI technologies.'],
            ['kode_pok' => '2.2.2', 'kode_owp' => '2.2.2.01', 'nama_komponen_detail' => 'Construction and equipment the pilot SI'],
            ['kode_pok' => '2.2.2', 'kode_owp' => '2.2.2.02', 'nama_komponen_detail' => 'Technical Guidance for farmers on smart farming'],
            ['kode_pok' => '3.1.1', 'kode_owp' => '3.1.1.01', 'nama_komponen_detail' => 'Construction of Post-harvest facilities'],
            ['kode_pok' => '3.1.1', 'kode_owp' => '3.1.1.02', 'nama_komponen_detail' => 'Equipment for post harvest facilities'],
            ['kode_pok' => '3.1.1', 'kode_owp' => '3.1.1.03', 'nama_komponen_detail' => 'Construction of Processing unit'],
            ['kode_pok' => '3.1.1', 'kode_owp' => '3.1.1.04', 'nama_komponen_detail' => 'Equipment for processing unit'],
            ['kode_pok' => '3.1.1', 'kode_owp' => '3.1.1.05', 'nama_komponen_detail' => 'Technical Guidance in post-harvest & Processing machinery for youth graduated from SMK teknik mesin'],
            ['kode_pok' => '3.1.2', 'kode_owp' => '3.1.2.01', 'nama_komponen_detail' => 'Construction of Integrated Packing house facilities'],
            ['kode_pok' => '3.1.2', 'kode_owp' => '3.1.2.02', 'nama_komponen_detail' => 'Equipment for Integrated Packing house facilities'],
            ['kode_pok' => '3.1.3', 'kode_owp' => '3.1.3.01', 'nama_komponen_detail' => 'Technical Guidance for Processing'],
            ['kode_pok' => '3.1.3', 'kode_owp' => '3.1.3.02', 'nama_komponen_detail' => 'Technical Guidance in Good Manufacturing Practice'],
            ['kode_pok' => '3.1.4', 'kode_owp' => '3.1.4.01', 'nama_komponen_detail' => 'Development of Post-Harvest and Horticulture Product Processing Business Groups'],
            ['kode_pok' => '3.1.4', 'kode_owp' => '3.1.4.02', 'nama_komponen_detail' => 'Farmer Field School on Business management'],
            ['kode_pok' => '3.1.5', 'kode_owp' => '3.1.5.01', 'nama_komponen_detail' => 'Consultations with Financial Services Authority (OJK) or other stakeholders, and workshops for financial literacy education'],
            ['kode_pok' => '3.1.5', 'kode_owp' => '3.1.5.02', 'nama_komponen_detail' => 'Farmer Field School on Financial literacy'],
            ['kode_pok' => '3.1.5', 'kode_owp' => '3.1.5.03', 'nama_komponen_detail' => 'Consultation and MoU with Financial Institution for Access to Loans'],
            ['kode_pok' => '3.1.6', 'kode_owp' => '3.1.6.01', 'nama_komponen_detail' => 'Coordination with the selected financial institutions'],
            ['kode_pok' => '3.2.1', 'kode_owp' => '3.2.1.01', 'nama_komponen_detail' => 'Consultations among MOA and related stakeholders for GAP implementation at HCs'],
            ['kode_pok' => '3.2.1', 'kode_owp' => '3.2.1.02', 'nama_komponen_detail' => 'Manuals or guidelines and curriculum preparation, including videos'],
            ['kode_pok' => '3.2.1', 'kode_owp' => '3.2.1.03', 'nama_komponen_detail' => 'Technical Guidance of LAs and Pemandu Lapang'],
            ['kode_pok' => '3.2.2', 'kode_owp' => '3.2.2.01', 'nama_komponen_detail' => 'Consultations among MOA and related stakeholders for GHP implementation'],
            ['kode_pok' => '3.2.2', 'kode_owp' => '3.2.2.02', 'nama_komponen_detail' => 'Manuals or guidelines and curriculum preparation, including videos'],
            ['kode_pok' => '3.2.2', 'kode_owp' => '3.2.2.03', 'nama_komponen_detail' => 'Consultations and workshops for GAP certification database'],
            ['kode_pok' => '3.2.3', 'kode_owp' => '3.2.3.01', 'nama_komponen_detail' => 'Farm/HC Registration and GAP Certification facilitation'],
            ['kode_pok' => '3.2.3', 'kode_owp' => '3.2.3.02', 'nama_komponen_detail' => 'Regular monitoring and evaluation as well as guidance for the certification at the farmers levels which comply to GAP standards'],
            ['kode_pok' => '3.3.1', 'kode_owp' => '3.3.1.01', 'nama_komponen_detail' => 'Consultation and workshops about business partnerships for horticulture clusters'],
            ['kode_pok' => '3.3.2', 'kode_owp' => '3.3.2.01', 'nama_komponen_detail' => 'Facilitation the farmer partnerships with private sector (Fintech and other Tech companies)'],
            ['kode_pok' => '3.3.3', 'kode_owp' => '3.3.3.01', 'nama_komponen_detail' => 'Horticulture Product Promotion'],
            ['kode_pok' => '3.3.3', 'kode_owp' => '3.3.3.02', 'nama_komponen_detail' => 'Facilitation of Promotional Materials for Horticulture Clusters'],
            ['kode_pok' => '3.4.1', 'kode_owp' => '3.4.1.01', 'nama_komponen_detail' => 'Maintenance of the existing traceability information system in horticulture clusters area'],
            ['kode_pok' => '3.4.1', 'kode_owp' => '3.4.1.02', 'nama_komponen_detail' => 'Development and maintenance the traceability information system in horticulture clusters area'],
            ['kode_pok' => '4.1.1', 'kode_owp' => '4.1.1.01', 'nama_komponen_detail' => 'Technical Guidance in climate change adaptation for PAA/DAA staffs and Fas'],
            ['kode_pok' => '4.1.2', 'kode_owp' => '4.1.2.01', 'nama_komponen_detail' => 'Technical Guidance for DGH staffs'],
            ['kode_pok' => '4.1.2', 'kode_owp' => '4.1.2.02', 'nama_komponen_detail' => 'Overseas Comparative study program'],
            ['kode_pok' => '4.1.3', 'kode_owp' => '4.1.3.01', 'nama_komponen_detail' => 'Technical Guidance for government staffs at central, provincial, and district level'],
            ['kode_pok' => '4.1.3', 'kode_owp' => '4.1.3.02', 'nama_komponen_detail' => 'Comparative study program'],
            ['kode_pok' => '4.1.4', 'kode_owp' => '4.1.4.01', 'nama_komponen_detail' => 'Selection of BDSPs/NGOs/PLUTs to support capacity building of organizations'],
            ['kode_pok' => '4.1.4', 'kode_owp' => '4.1.4.02', 'nama_komponen_detail' => 'Technical Guidance for farmers and farmers group'],
            ['kode_pok' => '4.1.4', 'kode_owp' => '4.1.4.03', 'nama_komponen_detail' => 'Facilitation of legalization of selected FOs into registered BUMDES or Cooperative'],
            ['kode_pok' => '4.1.4', 'kode_owp' => '4.1.4.04', 'nama_komponen_detail' => 'Facilitation of of registering selected FOs in the e-Catalog for supplying Vegetables to "Makan Bergizi Gratis" Program'],
            ['kode_pok' => '4.2.1', 'kode_owp' => '4.2.1.01', 'nama_komponen_detail' => 'NPMU-DGAIF-DGIL'],
            ['kode_pok' => '4.2.1', 'kode_owp' => '4.2.1.02', 'nama_komponen_detail' => 'Development of the Projects Management Information System'],
            ['kode_pok' => '4.2.1', 'kode_owp' => '4.2.1.03', 'nama_komponen_detail' => 'Technical Guidance of District Team'],
            ['kode_pok' => '4.2.1', 'kode_owp' => '4.2.1.04', 'nama_komponen_detail' => 'District Project Implementation Units (DPIU)'],
            ['kode_pok' => '4.2.1', 'kode_owp' => '4.2.1.05', 'nama_komponen_detail' => 'Technical Guidance of Project Management Annually'],
            ['kode_pok' => '4.2.2', 'kode_owp' => '4.2.2.01', 'nama_komponen_detail' => 'Baselines survey'],
            ['kode_pok' => '4.2.2', 'kode_owp' => '4.2.2.02', 'nama_komponen_detail' => 'Midterm Survey'],
            ['kode_pok' => '4.2.2', 'kode_owp' => '4.2.2.03', 'nama_komponen_detail' => 'Completion Survey'],
            ['kode_pok' => '4.2.2', 'kode_owp' => '4.2.2.04', 'nama_komponen_detail' => 'National Project Management Consultant'],
            ['kode_pok' => '4.2.2', 'kode_owp' => '4.2.2.05', 'nama_komponen_detail' => 'District Implementation Team (DIT) Sumatera Region'],
            ['kode_pok' => '4.2.2', 'kode_owp' => '4.2.2.06', 'nama_komponen_detail' => 'District Implementation Team (DIT) Java Region 1'],
            ['kode_pok' => '4.2.2', 'kode_owp' => '4.2.2.07', 'nama_komponen_detail' => 'District Implementation Team (DIT) Java Region 2'],
            ['kode_pok' => '4.2.2', 'kode_owp' => '4.2.2.08', 'nama_komponen_detail' => 'District Implementation Team (DIT) Sulawesi'],
            ['kode_pok' => '4.2.2', 'kode_owp' => '4.2.2.09', 'nama_komponen_detail' => 'District Implementation Team (DIT) East Nusa Tenggara'],
            ['kode_pok' => '4.2.2', 'kode_owp' => '4.2.2.10', 'nama_komponen_detail' => 'HDDAP HRD and Money Individual Consultants'],
            ['kode_pok' => '4.2.2', 'kode_owp' => '4.2.2.11', 'nama_komponen_detail' => 'Agriculture Sector Support Individual Consultants'],
            ['kode_pok' => '4.2.2', 'kode_owp' => '4.2.2.12', 'nama_komponen_detail' => 'Facilitator Individual Consultants'],
            ['kode_pok' => '4.2.2', 'kode_owp' => '4.2.2.13', 'nama_komponen_detail' => 'External Monitoring Agency (EMA) - West'],
            ['kode_pok' => '4.2.2', 'kode_owp' => '4.2.2.14', 'nama_komponen_detail' => 'External Monitoring Agency (EMA) - Central'],
            ['kode_pok' => '4.2.2', 'kode_owp' => '4.2.2.15', 'nama_komponen_detail' => 'External Monitoring Agency (EMA) - East'],
        ];

        foreach ($items as $item) {
            KeuanganSubKomponenDetail::updateOrCreate(
                ['kode_owp' => $item['kode_owp']],
                $item,
            );
        }
    }
}
